import { Server } from 'miragejs';
import { getModels, getSerializers } from './ember-data';
import { hasEmberData } from './utils/ember-data';

export { defaultPassthroughs } from 'miragejs';

/**
  @hide
*/
export default class EmberServer extends Server {

  constructor(options) {
    if (hasEmberData) {
      if (options.discoverEmberDataModels) {
        // Merge models from autogenerated Ember Data models with user defined models
        let models = getModels()
        options.models = Object.assign({}, models, options.models);
      }
      if (options.discoverEmberDataSerializers) {
        // Extend Merge serializers from autogenerated Ember Data serializers
        let serializers = getSerializers(options.serializers || {})
        // auto generated ones are extending the provided ones, so the assign is reverse of models
        options.serializers = Object.assign({}, options.serializers, serializers);
      }
    }

    super(options);


    if (typeof location !== 'undefined' && location.search.indexOf('mirageLogging') !== -1) {
      this.logging = true;
    }
  }

}
